# This file contains values from Cookiecutter

default_context:
  project_name: "epyt-c"
  project_description: "Awesome `epyt-c` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "SWIL-IITK"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "swil_iitk"
  email: "abhijith@iitk.ac.in"
  version: "0.1.0"
  line_length: "99"
  create_example_template: "none"
