# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: check epyt-c

on:
  push:
    branches: [ "main", "optimizing"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: build and install package
      run: |
        python -m build
        pip install dist/epytc-0.2.0-py3-none-any.whl
    - name: run run_sample.py
      run: python run_sample.py
    - name: run EX1 jupyter notebook
      run: |
        jupyter nbconvert --to script Examples/EX1_Adding_water_quality_input_values_for_source_nodes.ipynb
        python ./Examples/EX1_Adding_water_quality_input_values_for_source_nodes.py
